### ISSUE TITLE
Cannot run Pareto Anywhere on Docker

### ISSUE THREAD

**Issue by alwint3r** [reelyactive/pareto-anywhere#5]
Hi @jeffyactive,

I tried to run the Pareto Anywhere docker image but got the following error.

```
> pareto-anywhere@1.7.2 start /home
> node bin/pareto-anywhere

reelyActive barnowl instance is listening for an open IoT
reelyActive Barterer instance is exchanging data in an open IoT
reelyActive Chickadee instance is curious to associate metadata in an open IoT
reelyActive json-silo instance is hosting digital twins in an open IoT
barnowl-reel: UDP listening on 0.0.0.0:50000
barnowl-huawei: UDP listening on 0.0.0.0:50010
Pareto Anywhere by reelyActive is running on port 3001

/home/node_modules/levelup/lib/levelup.js:127
      return callback(new OpenError(err))
                      ^
Error [OpenError]: IO error: data/associations/LOCK: No such file or directory
    at /home/node_modules/levelup/lib/levelup.js:127:23
    at /home/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/home/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /home/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /home/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
Emitted 'error' event on LevelUP instance at:
    at /home/node_modules/levelup/lib/levelup.js:56:19
    at /home/node_modules/levelup/lib/levelup.js:127:14
    at /home/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    [... lines matching original stack trace ...]
    at /home/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pareto-anywhere@1.7.2 start: `node bin/pareto-anywhere`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pareto-anywhere@1.7.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/reelyactive/.npm/_logs/2022-05-12T08_18_33_787Z-debug.log
```

Looking at the error message, it seems that somehow the middleware did not create the data/association directory. I tried adding the below line to the Dockerfile. It solved the problem.

```dockerfile
RUN mkdir -p data/associations data/images data/stories && \
    touch data/associations/LOCK data/images/LOCK data/stories/LOCK
```

If you are ok with this change, I can send a PR to solve the problem.

**Comment by jeffyactive** [comment]
Hi @alwint3r, I hadn't tested with Docker since we switched to ESMapDB (which writes to the data/... directories), thanks for catching this.  Please go ahead with the PR, thanks!
